<?php

/**
 * ReservationRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ReservationRoom extends BaseReservationRoom
{
}
