<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AddressCity', 'doctrine');

/**
 * BaseAddressCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $postal_code
 * @property string $insee_code
 * @property integer $address_country_id
 * @property AddressCountry $AddressCountry
 * @property Doctrine_Collection $Address
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getPostalCode()         Returns the current record's "postal_code" value
 * @method string              getInseeCode()          Returns the current record's "insee_code" value
 * @method integer             getAddressCountryId()   Returns the current record's "address_country_id" value
 * @method AddressCountry      getAddressCountry()     Returns the current record's "AddressCountry" value
 * @method Doctrine_Collection getAddress()            Returns the current record's "Address" collection
 * @method AddressCity         setId()                 Sets the current record's "id" value
 * @method AddressCity         setName()               Sets the current record's "name" value
 * @method AddressCity         setPostalCode()         Sets the current record's "postal_code" value
 * @method AddressCity         setInseeCode()          Sets the current record's "insee_code" value
 * @method AddressCity         setAddressCountryId()   Sets the current record's "address_country_id" value
 * @method AddressCity         setAddressCountry()     Sets the current record's "AddressCountry" value
 * @method AddressCity         setAddress()            Sets the current record's "Address" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAddressCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('address_city');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('postal_code', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('insee_code', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('address_country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AddressCountry', array(
             'local' => 'address_country_id',
             'foreign' => 'id'));

        $this->hasMany('Address', array(
             'local' => 'id',
             'foreign' => 'address_city_id'));
    }
}