<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GroupUser', 'doctrine');

/**
 * BaseGroupUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $group_id
 * @property integer $user_id
 * 
 * @method integer   getId()       Returns the current record's "id" value
 * @method integer   getGroupId()  Returns the current record's "group_id" value
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method GroupUser setId()       Sets the current record's "id" value
 * @method GroupUser setGroupId()  Sets the current record's "group_id" value
 * @method GroupUser setUserId()   Sets the current record's "user_id" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGroupUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}