<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActUnitaryService', 'doctrine');

/**
 * BaseActUnitaryService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $quantity
 * @property Doctrine_Collection $Act
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method integer             getQuantity() Returns the current record's "quantity" value
 * @method Doctrine_Collection getAct()      Returns the current record's "Act" collection
 * @method ActUnitaryService   setId()       Sets the current record's "id" value
 * @method ActUnitaryService   setQuantity() Sets the current record's "quantity" value
 * @method ActUnitaryService   setAct()      Sets the current record's "Act" collection
 * 
 * @package    epi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActUnitaryService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('act_unitary_service');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Act', array(
             'local' => 'id',
             'foreign' => 'act_unitary_service_id'));
    }
}