<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ComputerOs', 'doctrine');

/**
 * BaseComputerOs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property integer $computer_os_family_id
 * @property integer $sort_order
 * @property ComputerOsFamily $ComputerOsFamily
 * @property Doctrine_Collection $Computer
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getDesignation()           Returns the current record's "designation" value
 * @method integer             getComputerOsFamilyId()    Returns the current record's "computer_os_family_id" value
 * @method integer             getSortOrder()             Returns the current record's "sort_order" value
 * @method ComputerOsFamily    getComputerOsFamily()      Returns the current record's "ComputerOsFamily" value
 * @method Doctrine_Collection getComputer()              Returns the current record's "Computer" collection
 * @method ComputerOs          setId()                    Sets the current record's "id" value
 * @method ComputerOs          setDesignation()           Sets the current record's "designation" value
 * @method ComputerOs          setComputerOsFamilyId()    Sets the current record's "computer_os_family_id" value
 * @method ComputerOs          setSortOrder()             Sets the current record's "sort_order" value
 * @method ComputerOs          setComputerOsFamily()      Sets the current record's "ComputerOsFamily" value
 * @method ComputerOs          setComputer()              Sets the current record's "Computer" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseComputerOs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('computer_os');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('computer_os_family_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ComputerOsFamily', array(
             'local' => 'computer_os_family_id',
             'foreign' => 'id'));

        $this->hasMany('Computer', array(
             'local' => 'id',
             'foreign' => 'computer_os_id'));
    }
}