<?php

/**
 * ComputerOs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ComputerOs extends BaseComputerOs
{
  public function __toString()
  {
    if ($this->getDesignation() != null)
    	return $this->getDesignation();
    else
    	return __('No OS');
  }
}
