<?php

/**
 * ImputationCountableService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ImputationCountableService extends BaseImputationCountableService
{
	
	/**
	 * 
	 * @param integer $user_id
	 * @param integer $moderator_id
	 * @param integer $act_id
	 * @param integer $act_public_category_id
	 */
	public function preConfigure($user_id, $moderator_id, $act_id, $act_public_category_id = null){
		
		ParametersConfiguration::setUserPrefix(sfContext::getInstance()->getUser()->getAttribute('login'));
		
		//Get the user:
	  	$user = Doctrine::getTable('User')
	  		->findOneById($user_id);
	  		
	  	//Get the moderator:
	  	$moderator = Doctrine::getTable('Moderator')
	  		->findOneById($moderator_id);
	  		
	  	//Get the act:
	  	//Get the moderator:
	  	$act = Doctrine::getTable('Act')
	  		->findOneById($act_id);
	  	
	  	//Set the user
	  	$this->getImputation()->setUser($user);
	  	
	  	//If the parameter "follow moderator actions" have been checked: set the moderator for the object ImputationAccountTransaction
	  	if(ParametersConfiguration::getDefault('default_follow_moderator')){
	  		$this->getImputation()->setModerator($moderator);
	  	}else{
	  		//Otherwise, set it to null:
	  		$this->getImputation()->setModeratorId(null);
	  	}
	  	
	  	//Set the act
	  	$this->getImputation()->setAct($act);
	  	
	  	//Set the default initial value based on the quantity of the act:
	  	$this->setInitialValue($this->getImputation()->getAct()->getQuantity());
	  	
	  	//Set the imputation 'total' based on the act_price:
		$act_price = Doctrine::getTable('ActPrice')
		  				->findOneByActIdAndActPublicCategoryId($act_id, $act_public_category_id);
		  			
	  	if($act_price['value'] == -1){
	  		
	  		if($this->getImputation()->getAct()->getMonetaryAccount()){
	  			$this->getImputation()->setTotal($this->getImputation()->getAct()->getQuantity());
	  		}else{
	  			$this->getImputation()->setTotal(0);
	  		}
	  		
	  	}else{
	  		$this->getImputation()->setTotal($act_price['value']);
	  	}
	  	
	  	//Set the date (today by default):
	  	$this->getImputation()->setDate(date('m/d/Y H:i'));
	  	
	  	//Set the room, building, method of payment and unity id:
	  	$this->getImputation()->setRoomId(ImputationDefaultValues::getDefaultValueByType(
	  			ImputationDefaultValues::DEFAULT_ROOM, ImputationDefaultValues::COUNTABLE_SERVICE_TYPE));
	  			
	  	$this->getImputation()->setBuildingId(ImputationDefaultValues::getDefaultValueByType(
	  			ImputationDefaultValues::DEFAULT_BUILDING, ImputationDefaultValues::COUNTABLE_SERVICE_TYPE));
	  			
	  	$this->getImputation()->setMethodOfPaymentId(ParametersConfiguration::getDefault('default_method_of_payment'));
	  	
	  	$this->getImputation()->setUnityId($act->getUnityId());
	  			
	  	//Set the imputation type to 3:
	  	$this->getImputation()->setImputationType(ImputationDefaultValues::COUNTABLE_SERVICE_TYPE);
	}
	
	
	/**
	 * 
	 * @param integer $user_id
	 * @param integer $act_id
	 * @param float $value
	 * @param boolean $monetary
	 */
	public static function createAccountUser($user_id, $account_id){
		
		/* ------- ACCOUNT_USER CREATION ------- */
			
			//In order to link the user and the account, we need a AccountUser object:
			$account_user = new AccountUser();
			
			//Set its values:
			$account_user->setUserId($user_id);
			$account_user->setAccountId($account_id);
			
			//Save it:
			$saved_account_user = $account_user->save();
			
			return $account_id;
	}
}
