<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
  public function __toString()
  {
    return $this->getName()." ".$this->getSurname();
  }
  
  public function getAge()
  {
  	$birthDate=$this->getBirthdate();
  	$arr1 = explode('-', $birthDate);
	$arr2 = explode('/', date('Y/m/d'));
			
	if(($arr1[1] < $arr2[1]) || (($arr1[1] == $arr2[1]) && ($arr1[2] <= $arr2[2])))
	return $arr2[0] - $arr1[0];
			
	return $arr2[0] - $arr1[0] - 1;
  }
  
  public function setActPublicCategoryId($publicCategory)
  {
  	if($publicCategory == 0)
  	{
  		return $this->_set('act_public_category_id', null);
  	}
  	return $this->_set('act_public_category_id', $publicCategory);
  } 
  
  public function setUserAwarenessId($userAwareness)
  {
  	if($userAwareness == 0)
  	{
  		return $this->_set('user_awareness_id', null);
  	}
  	return $this->_set('user_awareness_id', $userAwareness);
  } 
  
  public function setUserSegId($userSeg)
  {
  	if($userSeg == 0)
  	{
  		return $this->_set('user_seg_id', null);
  	}
  	return $this->_set('user_seg_id', $userSeg);
  }
  
  public function setUserGenderId($userGender)
  {
  	if($userGender == null)
  	{
  		return $this->_set('user_gender_id', null);
  	}
  	return $this->_set('user_gender_id', $userGender);
  }
  
  
  
  public static function getNameAndSurname($id){
  	
  	$user = Doctrine::getTable('User')
  			->find($id);
  			
  	if(!is_null($user)){
  		
  		return $user->__toString();
  	}else{
  		return 'Unknown user';
  	}
  			
  			
  }
}
