<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActPurchase', 'doctrine');

/**
 * BaseActPurchase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Doctrine_Collection $Act
 * 
 * @method integer             getId()  Returns the current record's "id" value
 * @method Doctrine_Collection getAct() Returns the current record's "Act" collection
 * @method ActPurchase         setId()  Sets the current record's "id" value
 * @method ActPurchase         setAct() Sets the current record's "Act" collection
 * 
 * @package    epi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActPurchase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('act_purchase');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Act', array(
             'local' => 'id',
             'foreign' => 'act_purchase_id'));
    }
}