<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListsDetail', 'doctrine');

/**
 * BaseListsDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $lists_id
 * @property string $domain
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getListsId()  Returns the current record's "lists_id" value
 * @method string      getDomain()   Returns the current record's "domain" value
 * @method ListsDetail setId()       Sets the current record's "id" value
 * @method ListsDetail setListsId()  Sets the current record's "lists_id" value
 * @method ListsDetail setDomain()   Sets the current record's "domain" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseListsDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lists_detail');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('lists_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('domain', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}