<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Structure', 'doctrine');

/**
 * BaseStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $name
 * @property string $email
 * @property string $siret_number
 * @property string $logo_path
 * @property string $website
 * @property string $telephone_number
 * @property integer $address_id
 * @property Address $Address
 * 
 * @method string    getId()               Returns the current record's "id" value
 * @method string    getName()             Returns the current record's "name" value
 * @method string    getEmail()            Returns the current record's "email" value
 * @method string    getSiretNumber()      Returns the current record's "siret_number" value
 * @method string    getLogoPath()         Returns the current record's "logo_path" value
 * @method string    getWebsite()          Returns the current record's "website" value
 * @method string    getTelephoneNumber()  Returns the current record's "telephone_number" value
 * @method integer   getAddressId()        Returns the current record's "address_id" value
 * @method Address   getAddress()          Returns the current record's "Address" value
 * @method Structure setId()               Sets the current record's "id" value
 * @method Structure setName()             Sets the current record's "name" value
 * @method Structure setEmail()            Sets the current record's "email" value
 * @method Structure setSiretNumber()      Sets the current record's "siret_number" value
 * @method Structure setLogoPath()         Sets the current record's "logo_path" value
 * @method Structure setWebsite()          Sets the current record's "website" value
 * @method Structure setTelephoneNumber()  Sets the current record's "telephone_number" value
 * @method Structure setAddressId()        Sets the current record's "address_id" value
 * @method Structure setAddress()          Sets the current record's "Address" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseStructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure');
        $this->hasColumn('id', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('email', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('siret_number', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '250',
             ));
        $this->hasColumn('logo_path', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('website', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '250',
             ));
        $this->hasColumn('telephone_number', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('address_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));
    }
}