<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Financier', 'doctrine');

/**
 * BaseFinancier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $logo_path
 * @property string $comment
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getName()      Returns the current record's "name" value
 * @method string    getLogoPath()  Returns the current record's "logo_path" value
 * @method string    getComment()   Returns the current record's "comment" value
 * @method Financier setId()        Sets the current record's "id" value
 * @method Financier setName()      Sets the current record's "name" value
 * @method Financier setLogoPath()  Sets the current record's "logo_path" value
 * @method Financier setComment()   Sets the current record's "comment" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFinancier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('financier');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('logo_path', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('comment', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '250',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}