<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActPrice', 'doctrine');

/**
 * BaseActPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $act_id
 * @property integer $act_public_category_id
 * @property float $value
 * @property ActPublicCategory $ActPublicCategory
 * @property Act $Act
 * 
 * @method integer           getId()                     Returns the current record's "id" value
 * @method integer           getActId()                  Returns the current record's "act_id" value
 * @method integer           getActPublicCategoryId()    Returns the current record's "act_public_category_id" value
 * @method float             getValue()                  Returns the current record's "value" value
 * @method ActPublicCategory getActPublicCategory()      Returns the current record's "ActPublicCategory" value
 * @method Act               getAct()                    Returns the current record's "Act" value
 * @method ActPrice          setId()                     Sets the current record's "id" value
 * @method ActPrice          setActId()                  Sets the current record's "act_id" value
 * @method ActPrice          setActPublicCategoryId()    Sets the current record's "act_public_category_id" value
 * @method ActPrice          setValue()                  Sets the current record's "value" value
 * @method ActPrice          setActPublicCategory()      Sets the current record's "ActPublicCategory" value
 * @method ActPrice          setAct()                    Sets the current record's "Act" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActPrice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('act_price');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('act_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('act_public_category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('value', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActPublicCategory', array(
             'local' => 'act_public_category_id',
             'foreign' => 'id'));

        $this->hasOne('Act', array(
             'local' => 'act_id',
             'foreign' => 'id'));
    }
}