<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserSeg', 'doctrine');

/**
 * BaseUserSeg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property integer $sort_order
 * @property Doctrine_Collection $User
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDesignation() Returns the current record's "designation" value
 * @method integer             getSortOrder()   Returns the current record's "sort_order" value
 * @method Doctrine_Collection getUser()        Returns the current record's "User" collection
 * @method UserSeg             setId()          Sets the current record's "id" value
 * @method UserSeg             setDesignation() Sets the current record's "designation" value
 * @method UserSeg             setSortOrder()   Sets the current record's "sort_order" value
 * @method UserSeg             setUser()        Sets the current record's "User" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserSeg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_seg');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'user_seg_id'));
    }
}