<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AddressCountry', 'doctrine');

/**
 * BaseAddressCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $AddressCity
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getAddressCity() Returns the current record's "AddressCity" collection
 * @method AddressCountry      setId()          Sets the current record's "id" value
 * @method AddressCountry      setName()        Sets the current record's "name" value
 * @method AddressCountry      setAddressCity() Sets the current record's "AddressCity" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAddressCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('address_country');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AddressCity', array(
             'local' => 'id',
             'foreign' => 'address_country_id'));
    }
}