<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActPublicCategory', 'doctrine');

/**
 * BaseActPublicCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property integer $sort_order
 * @property integer $filter_id
 * @property Doctrine_Collection $ActPrice
 * @property Doctrine_Collection $User
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDesignation() Returns the current record's "designation" value
 * @method integer             getSortOrder()   Returns the current record's "sort_order" value
 * @method integer             getFilterId()    Returns the current record's "filter_id" value
 * @method Doctrine_Collection getActPrice()    Returns the current record's "ActPrice" collection
 * @method Doctrine_Collection getUser()        Returns the current record's "User" collection
 * @method ActPublicCategory   setId()          Sets the current record's "id" value
 * @method ActPublicCategory   setDesignation() Sets the current record's "designation" value
 * @method ActPublicCategory   setSortOrder()   Sets the current record's "sort_order" value
 * @method ActPublicCategory   setFilterId()    Sets the current record's "filter_id" value
 * @method ActPublicCategory   setActPrice()    Sets the current record's "ActPrice" collection
 * @method ActPublicCategory   setUser()        Sets the current record's "User" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActPublicCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('act_public_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('filter_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ActPrice', array(
             'local' => 'id',
             'foreign' => 'act_public_category_id'));

        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'act_public_category_id'));
    }
}