<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ReservationRoom', 'doctrine');

/**
 * BaseReservationRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reservation_id
 * @property integer $room_id
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property Reservation $Reservation
 * @property Room $Room
 * 
 * @method integer         getId()             Returns the current record's "id" value
 * @method integer         getReservationId()  Returns the current record's "reservation_id" value
 * @method integer         getRoomId()         Returns the current record's "room_id" value
 * @method timestamp       getStartDate()      Returns the current record's "start_date" value
 * @method timestamp       getEndDate()        Returns the current record's "end_date" value
 * @method Reservation     getReservation()    Returns the current record's "Reservation" value
 * @method Room            getRoom()           Returns the current record's "Room" value
 * @method ReservationRoom setId()             Sets the current record's "id" value
 * @method ReservationRoom setReservationId()  Sets the current record's "reservation_id" value
 * @method ReservationRoom setRoomId()         Sets the current record's "room_id" value
 * @method ReservationRoom setStartDate()      Sets the current record's "start_date" value
 * @method ReservationRoom setEndDate()        Sets the current record's "end_date" value
 * @method ReservationRoom setReservation()    Sets the current record's "Reservation" value
 * @method ReservationRoom setRoom()           Sets the current record's "Room" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseReservationRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reservation_room');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('reservation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('room_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('start_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('end_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reservation', array(
             'local' => 'reservation_id',
             'foreign' => 'id'));

        $this->hasOne('Room', array(
             'local' => 'room_id',
             'foreign' => 'id'));
    }
}