<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImputationMethodOfPayment', 'doctrine');

/**
 * BaseImputationMethodOfPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property integer $sort_order
 * @property Doctrine_Collection $Imputation
 * 
 * @method integer                   getId()          Returns the current record's "id" value
 * @method string                    getDesignation() Returns the current record's "designation" value
 * @method integer                   getSortOrder()   Returns the current record's "sort_order" value
 * @method Doctrine_Collection       getImputation()  Returns the current record's "Imputation" collection
 * @method ImputationMethodOfPayment setId()          Sets the current record's "id" value
 * @method ImputationMethodOfPayment setDesignation() Sets the current record's "designation" value
 * @method ImputationMethodOfPayment setSortOrder()   Sets the current record's "sort_order" value
 * @method ImputationMethodOfPayment setImputation()  Sets the current record's "Imputation" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseImputationMethodOfPayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imputation_method_of_payment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Imputation', array(
             'local' => 'id',
             'foreign' => 'method_of_payment_id'));
    }
}