<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActType', 'doctrine');

/**
 * BaseActType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property Doctrine_Collection $Act
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDesignation() Returns the current record's "designation" value
 * @method Doctrine_Collection getAct()         Returns the current record's "Act" collection
 * @method ActType             setId()          Sets the current record's "id" value
 * @method ActType             setDesignation() Sets the current record's "designation" value
 * @method ActType             setAct()         Sets the current record's "Act" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('act_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Act', array(
             'local' => 'id',
             'foreign' => 'act_type_id'));
    }
}