<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImputationCountableService', 'doctrine');

/**
 * BaseImputationCountableService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $initial_value
 * @property integer $imputation_id
 * @property Imputation $Imputation
 * 
 * @method integer                    getId()            Returns the current record's "id" value
 * @method float                      getInitialValue()  Returns the current record's "initial_value" value
 * @method integer                    getImputationId()  Returns the current record's "imputation_id" value
 * @method Imputation                 getImputation()    Returns the current record's "Imputation" value
 * @method ImputationCountableService setId()            Sets the current record's "id" value
 * @method ImputationCountableService setInitialValue()  Sets the current record's "initial_value" value
 * @method ImputationCountableService setImputationId()  Sets the current record's "imputation_id" value
 * @method ImputationCountableService setImputation()    Sets the current record's "Imputation" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseImputationCountableService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imputation_countable_service');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('initial_value', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imputation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Imputation', array(
             'local' => 'imputation_id',
             'foreign' => 'id'));
    }
}