<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ComputerOsFamily', 'doctrine');

/**
 * BaseComputerOsFamily
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $family
 * @property integer $sort_order
 * @property Doctrine_Collection $ComputerOs
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getFamily()     Returns the current record's "family" value
 * @method integer             getSortOrder()  Returns the current record's "sort_order" value
 * @method Doctrine_Collection getComputerOs() Returns the current record's "ComputerOs" collection
 * @method ComputerOsFamily    setId()         Sets the current record's "id" value
 * @method ComputerOsFamily    setFamily()     Sets the current record's "family" value
 * @method ComputerOsFamily    setSortOrder()  Sets the current record's "sort_order" value
 * @method ComputerOsFamily    setComputerOs() Sets the current record's "ComputerOs" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseComputerOsFamily extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('computer_os_family');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('family', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ComputerOs', array(
             'local' => 'id',
             'foreign' => 'computer_os_family_id'));
    }
}