<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Computer', 'doctrine');

/**
 * BaseComputer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $shortened_name
 * @property string $comment
 * @property integer $year
 * @property string $mac_address
 * @property string $ip_address
 * @property integer $room_id
 * @property integer $computer_machine_type_id
 * @property integer $computer_os_id
 * @property integer $computer_type_of_connexion_id
 * @property ComputerMachineType $ComputerMachineType
 * @property ComputerOs $ComputerOs
 * @property Room $Room
 * @property ComputerTypeOfConnexion $ComputerTypeOfConnexion
 * @property Doctrine_Collection $ImputationUnitaryService
 * @property Doctrine_Collection $ReservationComputer
 * 
 * @method integer                 getId()                            Returns the current record's "id" value
 * @method string                  getName()                          Returns the current record's "name" value
 * @method string                  getShortenedName()                 Returns the current record's "shortened_name" value
 * @method string                  getComment()                       Returns the current record's "comment" value
 * @method integer                 getYear()                          Returns the current record's "year" value
 * @method string                  getMacAddress()                    Returns the current record's "mac_address" value
 * @method string                  getIpAddress()                     Returns the current record's "ip_address" value
 * @method integer                 getRoomId()                        Returns the current record's "room_id" value
 * @method integer                 getComputerMachineTypeId()         Returns the current record's "computer_machine_type_id" value
 * @method integer                 getComputerOsId()                  Returns the current record's "computer_os_id" value
 * @method integer                 getComputerTypeOfConnexionId()     Returns the current record's "computer_type_of_connexion_id" value
 * @method ComputerMachineType     getComputerMachineType()           Returns the current record's "ComputerMachineType" value
 * @method ComputerOs              getComputerOs()                    Returns the current record's "ComputerOs" value
 * @method Room                    getRoom()                          Returns the current record's "Room" value
 * @method ComputerTypeOfConnexion getComputerTypeOfConnexion()       Returns the current record's "ComputerTypeOfConnexion" value
 * @method Doctrine_Collection     getImputationUnitaryService()      Returns the current record's "ImputationUnitaryService" collection
 * @method Doctrine_Collection     getReservationComputer()           Returns the current record's "ReservationComputer" collection
 * @method Computer                setId()                            Sets the current record's "id" value
 * @method Computer                setName()                          Sets the current record's "name" value
 * @method Computer                setShortenedName()                 Sets the current record's "shortened_name" value
 * @method Computer                setComment()                       Sets the current record's "comment" value
 * @method Computer                setYear()                          Sets the current record's "year" value
 * @method Computer                setMacAddress()                    Sets the current record's "mac_address" value
 * @method Computer                setIpAddress()                     Sets the current record's "ip_address" value
 * @method Computer                setRoomId()                        Sets the current record's "room_id" value
 * @method Computer                setComputerMachineTypeId()         Sets the current record's "computer_machine_type_id" value
 * @method Computer                setComputerOsId()                  Sets the current record's "computer_os_id" value
 * @method Computer                setComputerTypeOfConnexionId()     Sets the current record's "computer_type_of_connexion_id" value
 * @method Computer                setComputerMachineType()           Sets the current record's "ComputerMachineType" value
 * @method Computer                setComputerOs()                    Sets the current record's "ComputerOs" value
 * @method Computer                setRoom()                          Sets the current record's "Room" value
 * @method Computer                setComputerTypeOfConnexion()       Sets the current record's "ComputerTypeOfConnexion" value
 * @method Computer                setImputationUnitaryService()      Sets the current record's "ImputationUnitaryService" collection
 * @method Computer                setReservationComputer()           Sets the current record's "ReservationComputer" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseComputer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('computer');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('shortened_name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('comment', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '250',
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('mac_address', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('ip_address', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('room_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('computer_machine_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('computer_os_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('computer_type_of_connexion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ComputerMachineType', array(
             'local' => 'computer_machine_type_id',
             'foreign' => 'id'));

        $this->hasOne('ComputerOs', array(
             'local' => 'computer_os_id',
             'foreign' => 'id'));

        $this->hasOne('Room', array(
             'local' => 'room_id',
             'foreign' => 'id'));

        $this->hasOne('ComputerTypeOfConnexion', array(
             'local' => 'computer_type_of_connexion_id',
             'foreign' => 'id'));

        $this->hasMany('ImputationUnitaryService', array(
             'local' => 'id',
             'foreign' => 'computer_id'));

        $this->hasMany('ReservationComputer', array(
             'local' => 'id',
             'foreign' => 'computer_id'));
    }
}