<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Event', 'doctrine');

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property string $description
 * @property integer $reservation_id
 * @property Reservation $Reservation
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method string      getDesignation()    Returns the current record's "designation" value
 * @method string      getDescription()    Returns the current record's "description" value
 * @method integer     getReservationId()  Returns the current record's "reservation_id" value
 * @method Reservation getReservation()    Returns the current record's "Reservation" value
 * @method Event       setId()             Sets the current record's "id" value
 * @method Event       setDesignation()    Sets the current record's "designation" value
 * @method Event       setDescription()    Sets the current record's "description" value
 * @method Event       setReservationId()  Sets the current record's "reservation_id" value
 * @method Event       setReservation()    Sets the current record's "Reservation" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('reservation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reservation', array(
             'local' => 'reservation_id',
             'foreign' => 'id'));
    }
}