<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Unity', 'doctrine');

/**
 * BaseUnity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property string $shortened_designation
 * @property integer $disabled
 * @property integer $sort_order
 * @property Doctrine_Collection $Act
 * @property Doctrine_Collection $Imputation
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getDesignation()           Returns the current record's "designation" value
 * @method string              getShortenedDesignation()  Returns the current record's "shortened_designation" value
 * @method integer             getDisabled()              Returns the current record's "disabled" value
 * @method integer             getSortOrder()             Returns the current record's "sort_order" value
 * @method Doctrine_Collection getAct()                   Returns the current record's "Act" collection
 * @method Doctrine_Collection getImputation()            Returns the current record's "Imputation" collection
 * @method Unity               setId()                    Sets the current record's "id" value
 * @method Unity               setDesignation()           Sets the current record's "designation" value
 * @method Unity               setShortenedDesignation()  Sets the current record's "shortened_designation" value
 * @method Unity               setDisabled()              Sets the current record's "disabled" value
 * @method Unity               setSortOrder()             Sets the current record's "sort_order" value
 * @method Unity               setAct()                   Sets the current record's "Act" collection
 * @method Unity               setImputation()            Sets the current record's "Imputation" collection
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUnity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unity');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('shortened_designation', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('disabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Act', array(
             'local' => 'id',
             'foreign' => 'unity_id'));

        $this->hasMany('Imputation', array(
             'local' => 'id',
             'foreign' => 'unity_id'));
    }
}