<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImputationAccountTransaction', 'doctrine');

/**
 * BaseImputationAccountTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $designation
 * @property float $sum
 * @property integer $imputation_id
 * @property Imputation $Imputation
 * 
 * @method integer                      getId()            Returns the current record's "id" value
 * @method string                       getDesignation()   Returns the current record's "designation" value
 * @method float                        getSum()           Returns the current record's "sum" value
 * @method integer                      getImputationId()  Returns the current record's "imputation_id" value
 * @method Imputation                   getImputation()    Returns the current record's "Imputation" value
 * @method ImputationAccountTransaction setId()            Sets the current record's "id" value
 * @method ImputationAccountTransaction setDesignation()   Sets the current record's "designation" value
 * @method ImputationAccountTransaction setSum()           Sets the current record's "sum" value
 * @method ImputationAccountTransaction setImputationId()  Sets the current record's "imputation_id" value
 * @method ImputationAccountTransaction setImputation()    Sets the current record's "Imputation" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseImputationAccountTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imputation_account_transaction');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('designation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('sum', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imputation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Imputation', array(
             'local' => 'imputation_id',
             'foreign' => 'id'));
    }
}