<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Listfilter', 'doctrine');

/**
 * BaseListfilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $list_id
 * @property integer $filter_id
 * @property integer $order
 * @property Filter $Filter
 * @property Lists $Lists
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method integer    getListId()    Returns the current record's "list_id" value
 * @method integer    getFilterId()  Returns the current record's "filter_id" value
 * @method integer    getOrder()     Returns the current record's "order" value
 * @method Filter     getFilter()    Returns the current record's "Filter" value
 * @method Lists      getLists()     Returns the current record's "Lists" value
 * @method Listfilter setId()        Sets the current record's "id" value
 * @method Listfilter setListId()    Sets the current record's "list_id" value
 * @method Listfilter setFilterId()  Sets the current record's "filter_id" value
 * @method Listfilter setOrder()     Sets the current record's "order" value
 * @method Listfilter setFilter()    Sets the current record's "Filter" value
 * @method Listfilter setLists()     Sets the current record's "Lists" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseListfilter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listfilter');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('list_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('filter_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Filter', array(
             'local' => 'filter_id',
             'foreign' => 'id'));

        $this->hasOne('Lists', array(
             'local' => 'list_id',
             'foreign' => 'id'));
    }
}