<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ReservationComputer', 'doctrine');

/**
 * BaseReservationComputer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reservation_id
 * @property integer $computer_id
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property Reservation $Reservation
 * @property Computer $Computer
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getReservationId()  Returns the current record's "reservation_id" value
 * @method integer             getComputerId()     Returns the current record's "computer_id" value
 * @method timestamp           getStartDate()      Returns the current record's "start_date" value
 * @method timestamp           getEndDate()        Returns the current record's "end_date" value
 * @method Reservation         getReservation()    Returns the current record's "Reservation" value
 * @method Computer            getComputer()       Returns the current record's "Computer" value
 * @method ReservationComputer setId()             Sets the current record's "id" value
 * @method ReservationComputer setReservationId()  Sets the current record's "reservation_id" value
 * @method ReservationComputer setComputerId()     Sets the current record's "computer_id" value
 * @method ReservationComputer setStartDate()      Sets the current record's "start_date" value
 * @method ReservationComputer setEndDate()        Sets the current record's "end_date" value
 * @method ReservationComputer setReservation()    Sets the current record's "Reservation" value
 * @method ReservationComputer setComputer()       Sets the current record's "Computer" value
 * 
 * @package    GENEPI
 * @subpackage model
 * @author     Pierre Boitel, Bastien Libersa, Paul Périé
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseReservationComputer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reservation_computer');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('reservation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('computer_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('start_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('end_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reservation', array(
             'local' => 'reservation_id',
             'foreign' => 'id'));

        $this->hasOne('Computer', array(
             'local' => 'computer_id',
             'foreign' => 'id'));
    }
}