<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/12/16 15:25:43
sfConfig::add(array(
  'ex_meta_creator' => 'firstname lastname',
  'ex_meta_title' => 'title',
  'ex_meta_subject' => 'subject',
  'ex_meta_description' => 'description',
  'ex_meta_keywords' => 'keywords',
  'ex_meta_category' => 'category',
));
