<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/12/16 15:25:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=pyxis.kyxar.fr;dbname=epi_dev_kyxar;port=3306',
  'username' => 'polenum',
  'password' => 'parToutatis45!',
  'name' => 'doctrine',
)),);
