<?php
// auto-generated by sfCacheConfigHandler
// date: 2013/12/17 10:18:03
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

